# Generated by Django 5.0.7 on 2024-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
